//
//  Accommodation.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct Accommodation {
    let query = "Accommodation"
    lazy var accommodationVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Accommodation", translatedText: "숙박시설", realmQeury: query),
        RealmVocaModel(sourceText: "Hotel", translatedText: "호텔", realmQeury: query),
        RealmVocaModel(sourceText: "Motel", translatedText: "모텔", realmQeury: query),
        RealmVocaModel(sourceText: "Inn", translatedText: "여관", realmQeury: query),
        RealmVocaModel(sourceText: "Hostel", translatedText: "호스텔", realmQeury: query),
        RealmVocaModel(sourceText: "Lodge", translatedText: "숙소", realmQeury: query),
        RealmVocaModel(sourceText: "Resort", translatedText: "리조트", realmQeury: query),
        RealmVocaModel(sourceText: "Guesthouse", translatedText: "게스트하우스", realmQeury: query),
        RealmVocaModel(sourceText: "B&B (Bed and Breakfast)", translatedText: "B&B(민박)", realmQeury: query),
        RealmVocaModel(sourceText: "Cabin", translatedText: "오두막", realmQeury: query),
        RealmVocaModel(sourceText: "Campground", translatedText: "캠핑장", realmQeury: query),
        RealmVocaModel(sourceText: "Host/Hostess", translatedText: "호스트/호스티스", realmQeury: query),
        RealmVocaModel(sourceText: "Front Desk", translatedText: " 프런트 데스크", realmQeury: query),
        RealmVocaModel(sourceText: "Check-in", translatedText: "체크인", realmQeury: query),
        RealmVocaModel(sourceText: "Check-out", translatedText: "체크아웃", realmQeury: query),
        RealmVocaModel(sourceText: "Reservation", translatedText: "예약", realmQeury: query),
        RealmVocaModel(sourceText: "Room Service", translatedText: "룸 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Suite", translatedText: "스위트룸", realmQeury: query),
        RealmVocaModel(sourceText: "Single Room", translatedText: "싱글룸", realmQeury: query),
        RealmVocaModel(sourceText: "Double Room", translatedText: "더블룸", realmQeury: query),
        RealmVocaModel(sourceText: "Twin Room", translatedText: "트윈룸", realmQeury: query),
        RealmVocaModel(sourceText: "Triple Room", translatedText: "트리플룸", realmQeury: query),
        RealmVocaModel(sourceText: "Amenities", translatedText: "편의시설", realmQeury: query),
        RealmVocaModel(sourceText: "Facilities", translatedText: "시설", realmQeury: query),
        RealmVocaModel(sourceText: "Air Conditioning", translatedText: "에어컨", realmQeury: query),
        RealmVocaModel(sourceText: "Heating", translatedText: "난방", realmQeury: query),
        RealmVocaModel(sourceText: "Wi-Fi", translatedText: "와이파이", realmQeury: query),
        RealmVocaModel(sourceText: "TV", translatedText: "텔레비전", realmQeury: query),
        RealmVocaModel(sourceText: "Mini-bar", translatedText: "미니바", realmQeury: query),
        RealmVocaModel(sourceText: "Safe", translatedText: "금고", realmQeury: query),
        RealmVocaModel(sourceText: "Shower", translatedText: "샤워", realmQeury: query),
        RealmVocaModel(sourceText: "Bathtub", translatedText: "욕조", realmQeury: query),
        RealmVocaModel(sourceText: "Toiletries", translatedText: "화장품", realmQeury: query),
        RealmVocaModel(sourceText: "Towels", translatedText: "수건", realmQeury: query),
        RealmVocaModel(sourceText: "Bedding", translatedText: "침구", realmQeury: query),
        RealmVocaModel(sourceText: "Pillow", translatedText: "베개", realmQeury: query),
        RealmVocaModel(sourceText: "Blanket", translatedText: "담요", realmQeury: query),
        RealmVocaModel(sourceText: "Linen", translatedText: "리넨", realmQeury: query),
        RealmVocaModel(sourceText: "Key Card", translatedText: "키 카드", realmQeury: query),
        RealmVocaModel(sourceText: "Do Not Disturb", translatedText: "방해 금지", realmQeury: query),
        RealmVocaModel(sourceText: "Housekeeping", translatedText: "하우스키퍼", realmQeury: query),
        RealmVocaModel(sourceText: "Concierge", translatedText: "콘시어지", realmQeury: query),
        RealmVocaModel(sourceText: "Bellboy/Porter", translatedText: "케리어 보이", realmQeury: query),
        RealmVocaModel(sourceText: "Lobby", translatedText: "로비", realmQeury: query),
        RealmVocaModel(sourceText: "Restaurant", translatedText: "레스토랑", realmQeury: query),
        RealmVocaModel(sourceText: "Bar", translatedText: "바", realmQeury: query),
        RealmVocaModel(sourceText: "Café", translatedText: "카페", realmQeury: query),
        RealmVocaModel(sourceText: "Room Type", translatedText: "객실 유형", realmQeury: query),
        RealmVocaModel(sourceText: "Reservation Confirmation", translatedText: "예약 확인", realmQeury: query),
        RealmVocaModel(sourceText: "Extra Bed", translatedText: "여분 침대", realmQeury: query),
        RealmVocaModel(sourceText: "Late Check-out", translatedText: "늦은 체크아웃", realmQeury: query),
        RealmVocaModel(sourceText: "Early Check-in", translatedText: "이른 체크인", realmQeury: query),
        RealmVocaModel(sourceText: "Vacancy", translatedText: "빈 객실", realmQeury: query),
        RealmVocaModel(sourceText: "Occupied", translatedText: "이용 중", realmQeury: query),
        RealmVocaModel(sourceText: "Full Occupancy", translatedText: "만실", realmQeury: query),
        RealmVocaModel(sourceText: "Vacancy Rate", translatedText: "빈방 비율", realmQeury: query),
        RealmVocaModel(sourceText: "Hotel Chain", translatedText: "호텔 체인", realmQeury: query),
        RealmVocaModel(sourceText: "Reservation Cancellation", translatedText: "예약 취소", realmQeury: query),
        RealmVocaModel(sourceText: "Front Office", translatedText: " 프런트 오피스", realmQeury: query),
        RealmVocaModel(sourceText: "Housekeeping Service", translatedText: "하우스키퍼 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Overbooking", translatedText: "과도 예약", realmQeury: query),
        RealmVocaModel(sourceText: "Bed and Breakfast", translatedText: "민박", realmQeury: query),
        RealmVocaModel(sourceText: "Backpacker Hostel", translatedText: "배낭 여행자 호스텔", realmQeury: query),
        RealmVocaModel(sourceText: "Room Rate", translatedText: "객실 요금", realmQeury: query),
        RealmVocaModel(sourceText: "Vacation Rental", translatedText: "휴가 임대", realmQeury: query),
        RealmVocaModel(sourceText: "Room Key", translatedText: "객실 열쇠", realmQeury: query),
        RealmVocaModel(sourceText: "View", translatedText: "전망", realmQeury: query),
        RealmVocaModel(sourceText: "Front Desk Clerk", translatedText: "프런트 데스크 직원", realmQeury: query),
        RealmVocaModel(sourceText: "Room Availability", translatedText: "객실 이용 가능 여부", realmQeury: query),
        RealmVocaModel(sourceText: "Group Reservation", translatedText: "단체 예약", realmQeury: query),
        RealmVocaModel(sourceText: "Hotel Manager", translatedText: "호텔 매니저", realmQeury: query),
        RealmVocaModel(sourceText: "Key Deposit", translatedText: "열쇠 보증금", realmQeury: query),
        RealmVocaModel(sourceText: "Turn-down Service", translatedText: "특별 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Accommodation Voucher", translatedText: "숙박권", realmQeury: query),
        RealmVocaModel(sourceText: "Cancellation Fee", translatedText: "취소 수수료", realmQeury: query),
        RealmVocaModel(sourceText: "Front Desk Agent", translatedText: "프런트 데스크 직원", realmQeury: query),
        RealmVocaModel(sourceText: "Hotel Directory", translatedText: "호텔 안내 디렉토리", realmQeury: query),
        RealmVocaModel(sourceText: "Hotel Room Service", translatedText: "호텔 룸 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Late Arrival", translatedText: "늦은 도착", realmQeury: query),
        RealmVocaModel(sourceText: "No-show", translatedText: "노쇼", realmQeury: query),
        RealmVocaModel(sourceText: "Room Assignment", translatedText: "객실 배정", realmQeury: query),
        RealmVocaModel(sourceText: "Room Change", translatedText: "객실 변경", realmQeury: query),
        RealmVocaModel(sourceText: "Room Upgrade", translatedText: "객실 업그레이드", realmQeury: query),
        RealmVocaModel(sourceText: "Vacation Home", translatedText: "휴가용 주택", realmQeury: query),
        RealmVocaModel(sourceText: "Tourist Accommodation", translatedText: "관광 숙박시설", realmQeury: query),
        RealmVocaModel(sourceText: "Front Desk Receptionist", translatedText: "프런트 데스크 접수원", realmQeury: query),
        RealmVocaModel(sourceText: "Reservation Policy", translatedText: "예약 정책", realmQeury: query),
        RealmVocaModel(sourceText: "Accommodation Options", translatedText: "숙박 옵션", realmQeury: query),
        RealmVocaModel(sourceText: "Front Desk Attendant", translatedText: "프런트 데스크 담당자", realmQeury: query),
        RealmVocaModel(sourceText: "Hostelry", translatedText: "숙박업", realmQeury: query),
        RealmVocaModel(sourceText: "Room Availability Status", translatedText: "객실 이용 가능 상태", realmQeury: query),
        RealmVocaModel(sourceText: "Hostel Dormitory", translatedText: "호스텔 기숙사", realmQeury: query),
        RealmVocaModel(sourceText: "Booking Confirmation", translatedText: "예약 확인", realmQeury: query),
        RealmVocaModel(sourceText: "Room Reservation", translatedText: "객실 예약", realmQeury: query),
        RealmVocaModel(sourceText: "Room Rate Plan", translatedText: "객실 요금 계획", realmQeury: query),
        RealmVocaModel(sourceText: "Accommodation Costs", translatedText: "숙박 비용", realmQeury: query),
        RealmVocaModel(sourceText: "Reservation System", translatedText: "예약 시스템", realmQeury: query),
        RealmVocaModel(sourceText: "Accommodation Facilities", translatedText: "숙박 시설", realmQeury: query)
    ]
}
