//
//  CommunicationtravelVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct CommunicationtravelVoca {
    var communicationVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Communication", translatedText: "소통"),
        RealmVocaModel(sourceText: "Conversation", translatedText: "대화"),
        RealmVocaModel(sourceText: "Dialogue", translatedText: "대화"),
        RealmVocaModel(sourceText: "Language", translatedText: "언어"),
        RealmVocaModel(sourceText: "Speech", translatedText: "말"),
        RealmVocaModel(sourceText: "Speaking", translatedText: "말하기"),
        RealmVocaModel(sourceText: "Listening", translatedText: "듣기"),
        RealmVocaModel(sourceText: "Writing", translatedText: "쓰기"),
        RealmVocaModel(sourceText: "Reading", translatedText: "읽기"),
        RealmVocaModel(sourceText: "Nonverbal communication", translatedText: "비언어적 소통"),
        RealmVocaModel(sourceText: "Body language", translatedText: "신체 언어"),
        RealmVocaModel(sourceText: "Gesture", translatedText: "제스처"),
        RealmVocaModel(sourceText: "Facial expression", translatedText: "얼굴 표정"),
        RealmVocaModel(sourceText: "Eye contact", translatedText: "눈맞춤"),
        RealmVocaModel(sourceText: "Tone", translatedText: "억양"),
        RealmVocaModel(sourceText: "Pitch", translatedText: "음높이"),
        RealmVocaModel(sourceText: "Volume", translatedText: "음량"),
        RealmVocaModel(sourceText: "Pause", translatedText: "일시정지"),
        RealmVocaModel(sourceText: "Articulation", translatedText: "발음"),
        RealmVocaModel(sourceText: "Clarity", translatedText: "명확함"),
        RealmVocaModel(sourceText: "Conciseness", translatedText: "간결함"),
        RealmVocaModel(sourceText: "Conversational skills", translatedText: "대화 기술"),
        RealmVocaModel(sourceText: "Active listening", translatedText: "적극적인 듣기"),
        RealmVocaModel(sourceText: "Empathy", translatedText: "공감"),
        RealmVocaModel(sourceText: "Feedback", translatedText: "피드백"),
        RealmVocaModel(sourceText: "Interpersonal skills", translatedText: "대인 관계 기술"),
        RealmVocaModel(sourceText: "Conflict resolution", translatedText: "갈등 해결"),
        RealmVocaModel(sourceText: "Negotiation", translatedText: "협상"),
        RealmVocaModel(sourceText: "Persuasion", translatedText: "설득"),
        RealmVocaModel(sourceText: "Presentation", translatedText: "발표"),
        RealmVocaModel(sourceText: "Public speaking", translatedText: "공개 연설"),
        RealmVocaModel(sourceText: "Oratory", translatedText: "법정 연설"),
        RealmVocaModel(sourceText: "Telecommunications", translatedText: "통신"),
        RealmVocaModel(sourceText: "Telephony", translatedText: "전화 통신"),
        RealmVocaModel(sourceText: "Mobile communication", translatedText: "모바일 통신"),
        RealmVocaModel(sourceText: "Internet communication", translatedText: "인터넷 통신"),
        RealmVocaModel(sourceText: "Email", translatedText: "이메일"),
        RealmVocaModel(sourceText: "Instant messaging", translatedText: "인스턴트 메시징"),
        RealmVocaModel(sourceText: "Chat", translatedText: "채팅"),
        RealmVocaModel(sourceText: "Video call", translatedText: "영상 통화"),
        RealmVocaModel(sourceText: "Conference call", translatedText: "회의 통화"),
        RealmVocaModel(sourceText: "Social media", translatedText: "소셜 미디어"),
        RealmVocaModel(sourceText: "Networking", translatedText: "네트워킹"),
        RealmVocaModel(sourceText: "Online forums", translatedText: "온라인 포럼"),
        RealmVocaModel(sourceText: "Blogging", translatedText: "블로깅"),
        RealmVocaModel(sourceText: "Vlogging", translatedText: "블로그 비디오"),
        RealmVocaModel(sourceText: "Podcasting", translatedText: "팟캐스팅"),
        RealmVocaModel(sourceText: "Social networking sites", translatedText: "소셜 네트워킹 사이트"),
        RealmVocaModel(sourceText: "Text message", translatedText: "문자 메시지"),
        RealmVocaModel(sourceText: "Emoji", translatedText: "이모지"),
        RealmVocaModel(sourceText: "Abbreviation", translatedText: "약어"),
        RealmVocaModel(sourceText: "Acronym", translatedText: "머리글자"),
        RealmVocaModel(sourceText: "Spelling", translatedText: "철자"),
        RealmVocaModel(sourceText: "Grammar", translatedText: "문법"),
        RealmVocaModel(sourceText: "Vocabulary", translatedText: "어휘"),
        RealmVocaModel(sourceText: "Idiom", translatedText: "관용구"),
        RealmVocaModel(sourceText: "Slang", translatedText: "슬랭"),
        RealmVocaModel(sourceText: "Proverb", translatedText: "속담"),
        RealmVocaModel(sourceText: "Translation", translatedText: "번역"),
        RealmVocaModel(sourceText: "Interpreter", translatedText: "통역사"),
        RealmVocaModel(sourceText: "Transcription", translatedText: "전사"),
        RealmVocaModel(sourceText: "Dictation", translatedText: "디큐먼트"),
        RealmVocaModel(sourceText: "Language barrier", translatedText: "언어 장벽"),
        RealmVocaModel(sourceText: "Communication barrier", translatedText: "소통 장벽"),
        RealmVocaModel(sourceText: "Miscommunication", translatedText: "오해"),
        RealmVocaModel(sourceText: "Cross-cultural communication", translatedText: "문화 간 소통"),
        RealmVocaModel(sourceText: "Effective communication", translatedText: "효과적인 소통"),
        RealmVocaModel(sourceText: "Ineffective communication", translatedText: "비효과적인 소통"),
        RealmVocaModel(sourceText: "Verbal communication", translatedText: "언어적 소통"),
        RealmVocaModel(sourceText: "Written communication", translatedText: "문서적 소통")
    ]

}
