//
//  CulturetravelVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct CulturetravelVoca {
    var cultureVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Culture", translatedText: "문화"),
        RealmVocaModel(sourceText: "Tradition", translatedText: "전통"),
        RealmVocaModel(sourceText: "Custom", translatedText: "습관"),
        RealmVocaModel(sourceText: "Heritage", translatedText: "유산"),
        RealmVocaModel(sourceText: "Cultural diversity", translatedText: "다양성"),
        RealmVocaModel(sourceText: "Cultural exchange", translatedText: "문화 교류"),
        RealmVocaModel(sourceText: "Cultural assimilation", translatedText: "문화 동화"),
        RealmVocaModel(sourceText: "Cultural identity", translatedText: "문화 정체성"),
        RealmVocaModel(sourceText: "Cultural heritage", translatedText: "문화 유산"),
        RealmVocaModel(sourceText: "Cultural values", translatedText: "문화 가치"),
        RealmVocaModel(sourceText: "Ethnicity", translatedText: "민족성"),
        RealmVocaModel(sourceText: "Multiculturalism", translatedText: "다문화주의"),
        RealmVocaModel(sourceText: "Folklore", translatedText: "민속"),
        RealmVocaModel(sourceText: "Art", translatedText: "미술"),
        RealmVocaModel(sourceText: "Music", translatedText: "음악"),
        RealmVocaModel(sourceText: "Dance", translatedText: "댄스"),
        RealmVocaModel(sourceText: "Literature", translatedText: "문학"),
        RealmVocaModel(sourceText: "Theater", translatedText: "연극"),
        RealmVocaModel(sourceText: "Film", translatedText: "영화"),
        RealmVocaModel(sourceText: "Cuisine", translatedText: "요리"),
        RealmVocaModel(sourceText: "Cultural celebration", translatedText: "문화 축제"),
        RealmVocaModel(sourceText: "Cultural event", translatedText: "문화 행사"),
        RealmVocaModel(sourceText: "Cultural performance", translatedText: "문화 공연"),
        RealmVocaModel(sourceText: "Artifacts", translatedText: "유물"),
        RealmVocaModel(sourceText: "Symbols", translatedText: "상징"),
        RealmVocaModel(sourceText: "Ritual", translatedText: "의식"),
        RealmVocaModel(sourceText: "Ceremony", translatedText: "의식"),
        RealmVocaModel(sourceText: "Language", translatedText: "언어"),
        RealmVocaModel(sourceText: "Religion", translatedText: "종교"),
        RealmVocaModel(sourceText: "Beliefs", translatedText: "신념"),
        RealmVocaModel(sourceText: "Values", translatedText: "가치"),
        RealmVocaModel(sourceText: "Norms", translatedText: "표준"),
        RealmVocaModel(sourceText: "Mores", translatedText: "풍습"),
        RealmVocaModel(sourceText: "Taboos", translatedText: "금기"),
        RealmVocaModel(sourceText: "Etiquette", translatedText: "에티켓"),
        RealmVocaModel(sourceText: "Behavior", translatedText: "행동"),
        RealmVocaModel(sourceText: "Cultural adaptation", translatedText: "문화 적응"),
        RealmVocaModel(sourceText: "Cultural shock", translatedText: "문화 충격"),
        RealmVocaModel(sourceText: "Cultural norms", translatedText: "문화 표준"),
        RealmVocaModel(sourceText: "Festival", translatedText: "축제"),
        RealmVocaModel(sourceText: "Celebration", translatedText: "경축"),
        RealmVocaModel(sourceText: "Holiday", translatedText: "휴일"),
        RealmVocaModel(sourceText: "National day", translatedText: "국경일"),
        RealmVocaModel(sourceText: "Ethnic celebration", translatedText: "민족 축제"),
        RealmVocaModel(sourceText: "Cultural museum", translatedText: "문화 박물관"),
        RealmVocaModel(sourceText: "Art gallery", translatedText: "미술관"),
        RealmVocaModel(sourceText: "Exhibition", translatedText: "전시회"),
        RealmVocaModel(sourceText: "Parade", translatedText: "퍼레이드"),
        RealmVocaModel(sourceText: "Cultural performance", translatedText: "문화 공연"),
        RealmVocaModel(sourceText: "Storytelling", translatedText: "이야기"),
        RealmVocaModel(sourceText: "Mythology", translatedText: "신화"),
        RealmVocaModel(sourceText: "Legends", translatedText: "전설"),
        RealmVocaModel(sourceText: "Superstitions", translatedText: "미신"),
        RealmVocaModel(sourceText: "Cultural education", translatedText: "문화 교육"),
        RealmVocaModel(sourceText: "Cultural awareness", translatedText: "문화 인식"),
        RealmVocaModel(sourceText: "Cultural exploration", translatedText: "문화 탐험"),
        RealmVocaModel(sourceText: "Cultural immersion", translatedText: "문화 몰입"),
        RealmVocaModel(sourceText: "Cultural studies", translatedText: "문화 연구"),
        RealmVocaModel(sourceText: "Cultural exchange program", translatedText: "문화 교류 프로그램"),
        RealmVocaModel(sourceText: "Cultural heritage site", translatedText: "문화 유산 지역"),
        RealmVocaModel(sourceText: "Cultural sensitivity", translatedText: "문화 감수성"),
        RealmVocaModel(sourceText: "Cultural understanding", translatedText: "문화 이해"),
        RealmVocaModel(sourceText: "Cultural integration", translatedText: "문화 통합"),
        RealmVocaModel(sourceText: "Cultural discovery", translatedText: "문화 발견"),
        RealmVocaModel(sourceText: "Cultural differences", translatedText: "문화 차이"),
        RealmVocaModel(sourceText: "Cultural similarities", translatedText: "문화 유사성"),
        RealmVocaModel(sourceText: "Cultural influence", translatedText: "문화 영향"),
        RealmVocaModel(sourceText: "Cultural exchange", translatedText: "문화 교류"),
        RealmVocaModel(sourceText: "Cultural interaction", translatedText: "문화 상호 작용"),
        RealmVocaModel(sourceText: "Cultural appreciation", translatedText: "문화 평가")
    ]

}
