//
//  DiningVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct DiningVoca {
    var diningVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Restaurant", translatedText: "레스토랑"),
        RealmVocaModel(sourceText: "Cafe", translatedText: "카페"),
        RealmVocaModel(sourceText: "Bistro", translatedText: "비스트로"),
        RealmVocaModel(sourceText: "Bar", translatedText: "바"),
        RealmVocaModel(sourceText: "Pub", translatedText: "펍"),
        RealmVocaModel(sourceText: "Tavern", translatedText: "타버나"),
        RealmVocaModel(sourceText: "Diner", translatedText: "다이너"),
        RealmVocaModel(sourceText: "Eatery", translatedText: "식당"),
        RealmVocaModel(sourceText: "Brasserie", translatedText: "브라스리"),
        RealmVocaModel(sourceText: "Buffet", translatedText: "뷔페"),
        RealmVocaModel(sourceText: "Cafeteria", translatedText: "카페테리아"),
        RealmVocaModel(sourceText: "Fast food restaurant", translatedText: "패스트 푸드 레스토랑"),
        RealmVocaModel(sourceText: "Fine dining", translatedText: "고급 음식점"),
        RealmVocaModel(sourceText: "Casual dining", translatedText: "캐주얼 다이닝"),
        RealmVocaModel(sourceText: "Family-style restaurant", translatedText: "가족 레스토랑"),
        RealmVocaModel(sourceText: "Pizzeria", translatedText: "피자 가게"),
        RealmVocaModel(sourceText: "Steakhouse", translatedText: "스테이크 하우스"),
        RealmVocaModel(sourceText: "Seafood restaurant", translatedText: "해산물 레스토랑"),
        RealmVocaModel(sourceText: "Vegetarian restaurant", translatedText: "채식주의 레스토랑"),
        RealmVocaModel(sourceText: "Vegan restaurant", translatedText: "비건 레스토랑"),
        RealmVocaModel(sourceText: "Sushi bar", translatedText: "스시 바"),
        RealmVocaModel(sourceText: "Noodle bar", translatedText: "국수 전문점"),
        RealmVocaModel(sourceText: "Tapas bar", translatedText: "타파스 바"),
        RealmVocaModel(sourceText: "Wine bar", translatedText: "와인 바"),
        RealmVocaModel(sourceText: "Cocktail bar", translatedText: "칵테일 바"),
        RealmVocaModel(sourceText: "Menu", translatedText: "메뉴"),
        RealmVocaModel(sourceText: "Reservation", translatedText: "예약"),
        RealmVocaModel(sourceText: "Table", translatedText: "테이블"),
        RealmVocaModel(sourceText: "Chair", translatedText: "의자"),
        RealmVocaModel(sourceText: "Waiter", translatedText: "웨이터"),
        RealmVocaModel(sourceText: "Waitress", translatedText: "웨이트리스"),
        RealmVocaModel(sourceText: "Server", translatedText: "서빙하는 사람"),
        RealmVocaModel(sourceText: "Host", translatedText: "주인"),
        RealmVocaModel(sourceText: "Hostess", translatedText: "여주인"),
        RealmVocaModel(sourceText: "Chef", translatedText: "셰프"),
        RealmVocaModel(sourceText: "Cook", translatedText: "요리사"),
        RealmVocaModel(sourceText: "Kitchen", translatedText: "주방"),
        RealmVocaModel(sourceText: "Dish", translatedText: "요리"),
        RealmVocaModel(sourceText: "Appetizer", translatedText: "전채"),
        RealmVocaModel(sourceText: "Main course", translatedText: "주요 요리"),
        RealmVocaModel(sourceText: "Dessert", translatedText: "디저트"),
        RealmVocaModel(sourceText: "Beverage", translatedText: "음료"),
        RealmVocaModel(sourceText: "Alcoholic beverage", translatedText: "주류"),
        RealmVocaModel(sourceText: "Non-alcoholic beverage", translatedText: "논알콜 음료"),
        RealmVocaModel(sourceText: "Water", translatedText: "물"),
        RealmVocaModel(sourceText: "Soda", translatedText: "탄산음료"),
        RealmVocaModel(sourceText: "Juice", translatedText: "주스"),
        RealmVocaModel(sourceText: "Coffee", translatedText: "커피"),
        RealmVocaModel(sourceText: "Tea", translatedText: "차"),
        RealmVocaModel(sourceText: "Wine", translatedText: "와인"),
        RealmVocaModel(sourceText: "Beer", translatedText: "맥주"),
        RealmVocaModel(sourceText: "Sake", translatedText: "사케"),
        RealmVocaModel(sourceText: "Whiskey", translatedText: "위스키"),
        RealmVocaModel(sourceText: "Vodka", translatedText: "보드카"),
        RealmVocaModel(sourceText: "Rum", translatedText: "럼"),
        RealmVocaModel(sourceText: "Brandy", translatedText: "브랜디"),
        RealmVocaModel(sourceText: "Cognac", translatedText: "꼬냑"),
        RealmVocaModel(sourceText: "Gin", translatedText: "진"),
        RealmVocaModel(sourceText: "Cocktail", translatedText: "칵테일"),
        RealmVocaModel(sourceText: "Mocktail", translatedText: "논알콜 칵테일"),
        RealmVocaModel(sourceText: "Tip", translatedText: "팁"),
        RealmVocaModel(sourceText: "Bill", translatedText: "계산서"),
        RealmVocaModel(sourceText: "Service charge", translatedText: "서비스 요금"),
        RealmVocaModel(sourceText: "Fine", translatedText: "벌금"),
        RealmVocaModel(sourceText: "Tipping etiquette", translatedText: "팁에 관한 에티켓"),
        RealmVocaModel(sourceText: "Allergies", translatedText: "알레르기"),
        RealmVocaModel(sourceText: "Gluten-free", translatedText: "글루텐 프리"),
        RealmVocaModel(sourceText: "Vegan", translatedText: "비건"),
        RealmVocaModel(sourceText: "Vegetarian", translatedText: "채식주의자"),
        RealmVocaModel(sourceText: "Menu card", translatedText: "메뉴 카드"),
        RealmVocaModel(sourceText: "Order", translatedText: "주문"),
        RealmVocaModel(sourceText: "Cuisine", translatedText: "요리법"),
        RealmVocaModel(sourceText: "Reservation", translatedText: "예약"),
        RealmVocaModel(sourceText: "Outdoor dining", translatedText: "야외 식사"),
        RealmVocaModel(sourceText: "Indoor dining", translatedText: "실내 식사"),
        RealmVocaModel(sourceText: "Takeout", translatedText: "테이크아웃"),
        RealmVocaModel(sourceText: "Dine-in", translatedText: "매장식사")
    ]

}
