//
//  FacilitiestravelVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct FacilitiestravelVoca {
    var facilitiesVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Facilities", translatedText: "시설"),
        RealmVocaModel(sourceText: "Amenities", translatedText: "편의 시설"),
        RealmVocaModel(sourceText: "Infrastructure", translatedText: "인프라"),
        RealmVocaModel(sourceText: "Building", translatedText: "건물"),
        RealmVocaModel(sourceText: "Structure", translatedText: "구조물"),
        RealmVocaModel(sourceText: "Property", translatedText: "재산"),
        RealmVocaModel(sourceText: "Premises", translatedText: "부지"),
        RealmVocaModel(sourceText: "Real estate", translatedText: "부동산"),
        RealmVocaModel(sourceText: "Venue", translatedText: "장소"),
        RealmVocaModel(sourceText: "Location", translatedText: "위치"),
        RealmVocaModel(sourceText: "Space", translatedText: "공간"),
        RealmVocaModel(sourceText: "Room", translatedText: "방"),
        RealmVocaModel(sourceText: "Hall", translatedText: "홀"),
        RealmVocaModel(sourceText: "Conference room", translatedText: "회의실"),
        RealmVocaModel(sourceText: "Auditorium", translatedText: "강당"),
        RealmVocaModel(sourceText: "Stadium", translatedText: "경기장"),
        RealmVocaModel(sourceText: "Arena", translatedText: "아레나"),
        RealmVocaModel(sourceText: "Facility management", translatedText: "시설 관리"),
        RealmVocaModel(sourceText: "Maintenance", translatedText: "유지 보수"),
        RealmVocaModel(sourceText: "Repairs", translatedText: "수리"),
        RealmVocaModel(sourceText: "Renovation", translatedText: "리모델링"),
        RealmVocaModel(sourceText: "Upgrade", translatedText: "업그레이드"),
        RealmVocaModel(sourceText: "Improvement", translatedText: "개선"),
        RealmVocaModel(sourceText: "Accessibility", translatedText: "접근성"),
        RealmVocaModel(sourceText: "Convenience", translatedText: "편의성"),
        RealmVocaModel(sourceText: "Functionality", translatedText: "기능성"),
        RealmVocaModel(sourceText: "Equipment", translatedText: "장비"),
        RealmVocaModel(sourceText: "Appliances", translatedText: "가전제품"),
        RealmVocaModel(sourceText: "Furniture", translatedText: "가구"),
        RealmVocaModel(sourceText: "Fixtures", translatedText: "고정 장치"),
        RealmVocaModel(sourceText: "Utilities", translatedText: "공공 시설"),
        RealmVocaModel(sourceText: "Electricity", translatedText: "전기"),
        RealmVocaModel(sourceText: "Water supply", translatedText: "수도 공급"),
        RealmVocaModel(sourceText: "Heating", translatedText: "난방"),
        RealmVocaModel(sourceText: "Ventilation", translatedText: "환기"),
        RealmVocaModel(sourceText: "Air conditioning", translatedText: "에어컨"),
        RealmVocaModel(sourceText: "Wi-Fi", translatedText: "와이파이"),
        RealmVocaModel(sourceText: "Internet access", translatedText: "인터넷 접속"),
        RealmVocaModel(sourceText: "Parking", translatedText: "주차장"),
        RealmVocaModel(sourceText: "Security", translatedText: "보안"),
        RealmVocaModel(sourceText: "Surveillance", translatedText: "감시"),
        RealmVocaModel(sourceText: "Safety measures", translatedText: "안전 조치"),
        RealmVocaModel(sourceText: "Emergency exits", translatedText: "비상 출구"),
        RealmVocaModel(sourceText: "Facility layout", translatedText: "시설 배치"),
        RealmVocaModel(sourceText: "Floor plan", translatedText: "바닥 구도"),
        RealmVocaModel(sourceText: "Blueprint", translatedText: "설계도"),
        RealmVocaModel(sourceText: "Signage", translatedText: "표지판"),
        RealmVocaModel(sourceText: "Labeling", translatedText: "라벨링"),
        RealmVocaModel(sourceText: "Information desk", translatedText: "안내 데스크"),
        RealmVocaModel(sourceText: "Reception", translatedText: "접수"),
        RealmVocaModel(sourceText: "Lobby", translatedText: "로비"),
        RealmVocaModel(sourceText: "Cafeteria", translatedText: "카페테리아"),
        RealmVocaModel(sourceText: "Restaurant", translatedText: "레스토랑"),
        RealmVocaModel(sourceText: "Kitchen", translatedText: "주방"),
        RealmVocaModel(sourceText: "Restroom", translatedText: "화장실"),
        RealmVocaModel(sourceText: "Bathroom", translatedText: "욕실"),
        RealmVocaModel(sourceText: "Shower", translatedText: "샤워"),
        RealmVocaModel(sourceText: "Locker room", translatedText: "탈의실"),
        RealmVocaModel(sourceText: "Laundry room", translatedText: "세탁실"),
        RealmVocaModel(sourceText: "Fitness center", translatedText: "피트니스 센터"),
        RealmVocaModel(sourceText: "Swimming pool", translatedText: "수영장"),
        RealmVocaModel(sourceText: "Gymnasium", translatedText: "체육관"),
        RealmVocaModel(sourceText: "Spa", translatedText: "스파"),
        RealmVocaModel(sourceText: "Sauna", translatedText: "사우나"),
        RealmVocaModel(sourceText: "Jacuzzi", translatedText: "자쿠지"),
        RealmVocaModel(sourceText: "Barbecue area", translatedText: "바베큐장"),
        RealmVocaModel(sourceText: "Playground", translatedText: "놀이터"),
        RealmVocaModel(sourceText: "Garden", translatedText: "정원"),
        RealmVocaModel(sourceText: "Patio", translatedText: "파티오"),
        RealmVocaModel(sourceText: "Terrace", translatedText: "테라스"),
        RealmVocaModel(sourceText: "Balcony", translatedText: "발코니"),
        RealmVocaModel(sourceText: "Roof deck", translatedText: "옥상 데크")
    ]

}
