//
//  LeisuretravelVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct LeisuretravelVoca {
    var leisureTravelVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Vacation", translatedText: "휴가"),
        RealmVocaModel(sourceText: "Holiday", translatedText: "휴일"),
        RealmVocaModel(sourceText: "Trip", translatedText: "여행"),
        RealmVocaModel(sourceText: "Journey", translatedText: "여정"),
        RealmVocaModel(sourceText: "Adventure", translatedText: "모험"),
        RealmVocaModel(sourceText: "Exploration", translatedText: "탐험"),
        RealmVocaModel(sourceText: "Getaway", translatedText: "탈출"),
        RealmVocaModel(sourceText: "Excursion", translatedText: "소풍"),
        RealmVocaModel(sourceText: "Tour", translatedText: "투어"),
        RealmVocaModel(sourceText: "Expedition", translatedText: "원정"),
        RealmVocaModel(sourceText: "Retreat", translatedText: "휴양지"),
        RealmVocaModel(sourceText: "Staycation", translatedText: "근교 여행"),
        RealmVocaModel(sourceText: "Camping", translatedText: "캠핑"),
        RealmVocaModel(sourceText: "Hiking", translatedText: "하이킹"),
        RealmVocaModel(sourceText: "Backpacking", translatedText: "배낭 여행"),
        RealmVocaModel(sourceText: "Road trip", translatedText: "도로 여행"),
        RealmVocaModel(sourceText: "Sightseeing", translatedText: "관광"),
        RealmVocaModel(sourceText: "City break", translatedText: "도시 여행"),
        RealmVocaModel(sourceText: "Beach holiday", translatedText: "해변 휴가"),
        RealmVocaModel(sourceText: "Island hopping", translatedText: "섬 여행"),
        RealmVocaModel(sourceText: "Cruise", translatedText: "크루즈 여행"),
        RealmVocaModel(sourceText: "Resort", translatedText: "리조트"),
        RealmVocaModel(sourceText: "Spa retreat", translatedText: "스파 휴양지"),
        RealmVocaModel(sourceText: "Luxury travel", translatedText: "고급 여행"),
        RealmVocaModel(sourceText: "Eco-tourism", translatedText: "생태 관광"),
        RealmVocaModel(sourceText: "Heritage tourism", translatedText: "문화 유산 관광"),
        RealmVocaModel(sourceText: "Voluntourism", translatedText: "자원 봉사 여행"),
        RealmVocaModel(sourceText: "Agritourism", translatedText: "농촌체험 여행"),
        RealmVocaModel(sourceText: "Food tourism", translatedText: "음식 관광"),
        RealmVocaModel(sourceText: "Wine tourism", translatedText: "와인 관광"),
        RealmVocaModel(sourceText: "Cultural tourism", translatedText: "문화 여행"),
        RealmVocaModel(sourceText: "Nature tourism", translatedText: "자연 관광"),
        RealmVocaModel(sourceText: "Adventure tourism", translatedText: "모험 여행"),
        RealmVocaModel(sourceText: "Wildlife tourism", translatedText: "야생동물 관광"),
        RealmVocaModel(sourceText: "Solo travel", translatedText: "혼자 여행"),
        RealmVocaModel(sourceText: "Group travel", translatedText: "단체 여행"),
        RealmVocaModel(sourceText: "Family vacation", translatedText: "가족 휴가"),
        RealmVocaModel(sourceText: "Couple's getaway", translatedText: "커플 여행"),
        RealmVocaModel(sourceText: "Adventure sports", translatedText: "모험 스포츠"),
        RealmVocaModel(sourceText: "Outdoor activities", translatedText: "야외 활동"),
        RealmVocaModel(sourceText: "Leisure time", translatedText: "여가 시간"),
        RealmVocaModel(sourceText: "Relaxation", translatedText: "휴식"),
        RealmVocaModel(sourceText: "Recreation", translatedText: "오락"),
        RealmVocaModel(sourceText: "Entertainment", translatedText: "엔터테인먼트"),
        RealmVocaModel(sourceText: "Fun", translatedText: "즐거움"),
        RealmVocaModel(sourceText: "Leisure activities", translatedText: "여가 활동"),
        RealmVocaModel(sourceText: "Outdoor fun", translatedText: "야외 즐거움"),
        RealmVocaModel(sourceText: "Indoor fun", translatedText: "실내 즐거움"),
        RealmVocaModel(sourceText: "Theme park", translatedText: "테마파크"),
        RealmVocaModel(sourceText: "Amusement park", translatedText: "놀이공원"),
        RealmVocaModel(sourceText: "Water park", translatedText: "워터파크"),
        RealmVocaModel(sourceText: "Zoo", translatedText: "동물원"),
        RealmVocaModel(sourceText: "Aquarium", translatedText: "수족관"),
        RealmVocaModel(sourceText: "Botanical garden", translatedText: "식물원"),
        RealmVocaModel(sourceText: "Museum", translatedText: "박물관"),
        RealmVocaModel(sourceText: "Art gallery", translatedText: "미술관"),
        RealmVocaModel(sourceText: "Theater", translatedText: "극장"),
        RealmVocaModel(sourceText: "Concert", translatedText: "콘서트"),
        RealmVocaModel(sourceText: "Festival", translatedText: "축제"),
        RealmVocaModel(sourceText: "Carnival", translatedText: "카니발"),
        RealmVocaModel(sourceText: "Celebration", translatedText: "축하"),
        RealmVocaModel(sourceText: "Party", translatedText: "파티"),
        RealmVocaModel(sourceText: "Picnic", translatedText: "소풍"),
        RealmVocaModel(sourceText: "Photography", translatedText: "사진촬영"),
        RealmVocaModel(sourceText: "Scenic views", translatedText: "경치"),
        RealmVocaModel(sourceText: "Sunset", translatedText: "일몰"),
        RealmVocaModel(sourceText: "Sunrise", translatedText: "일출"),
        RealmVocaModel(sourceText: "Beachcombing", translatedText: "해변 산책"),
        RealmVocaModel(sourceText: "Stargazing", translatedText: "별보기"),
        RealmVocaModel(sourceText: "Cultural experience", translatedText: "문화 경험"),
        RealmVocaModel(sourceText: "Local cuisine", translatedText: "현지 음식"),
        RealmVocaModel(sourceText: "Shopping", translatedText: "쇼핑"),
        RealmVocaModel(sourceText: "Souvenir", translatedText: "기념품"),
        RealmVocaModel(sourceText: "Memories", translatedText: "추억"),
        RealmVocaModel(sourceText: "Relaxing destination", translatedText: "휴양지"),
        RealmVocaModel(sourceText: "Scenic routes", translatedText: "경관 좋은 길")
    ]

}
