//
//  LeisuretravelVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct LeisuretravelVoca {
    let query = "LeisuretravelVoca"
    lazy var leisureTravelVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Vacation", translatedText: "휴가", realmQeury: query),
        RealmVocaModel(sourceText: "Holiday", translatedText: "휴일", realmQeury: query),
        RealmVocaModel(sourceText: "Trip", translatedText: "여행", realmQeury: query),
        RealmVocaModel(sourceText: "Journey", translatedText: "여정", realmQeury: query),
        RealmVocaModel(sourceText: "Adventure", translatedText: "모험", realmQeury: query),
        RealmVocaModel(sourceText: "Exploration", translatedText: "탐험", realmQeury: query),
        RealmVocaModel(sourceText: "Getaway", translatedText: "탈출", realmQeury: query),
        RealmVocaModel(sourceText: "Excursion", translatedText: "소풍", realmQeury: query),
        RealmVocaModel(sourceText: "Tour", translatedText: "투어", realmQeury: query),
        RealmVocaModel(sourceText: "Expedition", translatedText: "원정", realmQeury: query),
        RealmVocaModel(sourceText: "Retreat", translatedText: "휴양지", realmQeury: query),
        RealmVocaModel(sourceText: "Staycation", translatedText: "근교 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Camping", translatedText: "캠핑", realmQeury: query),
        RealmVocaModel(sourceText: "Hiking", translatedText: "하이킹", realmQeury: query),
        RealmVocaModel(sourceText: "Backpacking", translatedText: "배낭 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Road trip", translatedText: "도로 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Sightseeing", translatedText: "관광", realmQeury: query),
        RealmVocaModel(sourceText: "City break", translatedText: "도시 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Beach holiday", translatedText: "해변 휴가", realmQeury: query),
        RealmVocaModel(sourceText: "Island hopping", translatedText: "섬 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Cruise", translatedText: "크루즈 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Resort", translatedText: "리조트", realmQeury: query),
        RealmVocaModel(sourceText: "Spa retreat", translatedText: "스파 휴양지", realmQeury: query),
        RealmVocaModel(sourceText: "Luxury travel", translatedText: "고급 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Eco-tourism", translatedText: "생태 관광", realmQeury: query),
        RealmVocaModel(sourceText: "Heritage tourism", translatedText: "문화 유산 관광", realmQeury: query),
        RealmVocaModel(sourceText: "Voluntourism", translatedText: "자원 봉사 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Agritourism", translatedText: "농촌체험 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Food tourism", translatedText: "음식 관광", realmQeury: query),
        RealmVocaModel(sourceText: "Wine tourism", translatedText: "와인 관광", realmQeury: query),
        RealmVocaModel(sourceText: "Cultural tourism", translatedText: "문화 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Nature tourism", translatedText: "자연 관광", realmQeury: query),
        RealmVocaModel(sourceText: "Adventure tourism", translatedText: "모험 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Wildlife tourism", translatedText: "야생동물 관광", realmQeury: query),
        RealmVocaModel(sourceText: "Solo travel", translatedText: "혼자 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Group travel", translatedText: "단체 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Family vacation", translatedText: "가족 휴가", realmQeury: query),
        RealmVocaModel(sourceText: "Couple's getaway", translatedText: "커플 여행", realmQeury: query),
        RealmVocaModel(sourceText: "Adventure sports", translatedText: "모험 스포츠", realmQeury: query),
        RealmVocaModel(sourceText: "Outdoor activities", translatedText: "야외 활동", realmQeury: query),
        RealmVocaModel(sourceText: "Leisure time", translatedText: "여가 시간", realmQeury: query),
        RealmVocaModel(sourceText: "Relaxation", translatedText: "휴식", realmQeury: query),
        RealmVocaModel(sourceText: "Recreation", translatedText: "오락", realmQeury: query),
        RealmVocaModel(sourceText: "Entertainment", translatedText: "엔터테인먼트", realmQeury: query),
        RealmVocaModel(sourceText: "Fun", translatedText: "즐거움", realmQeury: query),
        RealmVocaModel(sourceText: "Leisure activities", translatedText: "여가 활동", realmQeury: query),
        RealmVocaModel(sourceText: "Outdoor fun", translatedText: "야외 즐거움", realmQeury: query),
        RealmVocaModel(sourceText: "Indoor fun", translatedText: "실내 즐거움", realmQeury: query),
        RealmVocaModel(sourceText: "Theme park", translatedText: "테마파크", realmQeury: query),
        RealmVocaModel(sourceText: "Amusement park", translatedText: "놀이공원", realmQeury: query),
        RealmVocaModel(sourceText: "Water park", translatedText: "워터파크", realmQeury: query),
        RealmVocaModel(sourceText: "Zoo", translatedText: "동물원", realmQeury: query),
        RealmVocaModel(sourceText: "Aquarium", translatedText: "수족관", realmQeury: query),
        RealmVocaModel(sourceText: "Botanical garden", translatedText: "식물원", realmQeury: query),
        RealmVocaModel(sourceText: "Museum", translatedText: "박물관", realmQeury: query),
        RealmVocaModel(sourceText: "Art gallery", translatedText: "미술관", realmQeury: query),
        RealmVocaModel(sourceText: "Theater", translatedText: "극장", realmQeury: query),
        RealmVocaModel(sourceText: "Concert", translatedText: "콘서트", realmQeury: query),
        RealmVocaModel(sourceText: "Festival", translatedText: "축제", realmQeury: query),
        RealmVocaModel(sourceText: "Carnival", translatedText: "카니발", realmQeury: query),
        RealmVocaModel(sourceText: "Celebration", translatedText: "축하", realmQeury: query),
        RealmVocaModel(sourceText: "Party", translatedText: "파티", realmQeury: query),
        RealmVocaModel(sourceText: "Picnic", translatedText: "소풍", realmQeury: query),
        RealmVocaModel(sourceText: "Photography", translatedText: "사진촬영", realmQeury: query),
        RealmVocaModel(sourceText: "Scenic views", translatedText: "경치", realmQeury: query),
        RealmVocaModel(sourceText: "Sunset", translatedText: "일몰", realmQeury: query),
        RealmVocaModel(sourceText: "Sunrise", translatedText: "일출", realmQeury: query),
        RealmVocaModel(sourceText: "Beachcombing", translatedText: "해변 산책", realmQeury: query),
        RealmVocaModel(sourceText: "Stargazing", translatedText: "별보기", realmQeury: query),
        RealmVocaModel(sourceText: "Cultural experience", translatedText: "문화 경험", realmQeury: query),
        RealmVocaModel(sourceText: "Local cuisine", translatedText: "현지 음식", realmQeury: query),
        RealmVocaModel(sourceText: "Shopping", translatedText: "쇼핑", realmQeury: query),
        RealmVocaModel(sourceText: "Souvenir", translatedText: "기념품", realmQeury: query),
        RealmVocaModel(sourceText: "Memories", translatedText: "추억", realmQeury: query),
        RealmVocaModel(sourceText: "Relaxing destination", translatedText: "휴양지", realmQeury: query),
        RealmVocaModel(sourceText: "Scenic routes", translatedText: "경관 좋은 길", realmQeury: query)
    ]

}
