//
//  Transportation.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct Transportation {
    var transportationVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Vehicle", translatedText: "차량"),
        RealmVocaModel(sourceText: "Car", translatedText: "자동차"),
        RealmVocaModel(sourceText: "Truck", translatedText: "트럭"),
        RealmVocaModel(sourceText: "Bus", translatedText: "버스"),
        RealmVocaModel(sourceText: "Bicycle", translatedText: "자전거"),
        RealmVocaModel(sourceText: "Motorcycle", translatedText: "오토바이"),
        RealmVocaModel(sourceText: "Train", translatedText: "기차"),
        RealmVocaModel(sourceText: "Subway", translatedText: "지하철"),
        RealmVocaModel(sourceText: "Boat", translatedText: "보트"),
        RealmVocaModel(sourceText: "Ship", translatedText: "배"),
        RealmVocaModel(sourceText: "Aircraft", translatedText: "항공기"),
        RealmVocaModel(sourceText: "Airplane", translatedText: "비행기"),
        RealmVocaModel(sourceText: "Helicopter", translatedText: "헬리콥터"),
        RealmVocaModel(sourceText: "Van", translatedText: "밴"),
        RealmVocaModel(sourceText: "Scooter", translatedText: "스쿠터"),
        RealmVocaModel(sourceText: "Taxi", translatedText: "택시"),
        RealmVocaModel(sourceText: "RV (Recreational Vehicle)", translatedText: "RV(레크리에이션 차량)"),
        RealmVocaModel(sourceText: "Trailer", translatedText: "트레일러"),
        RealmVocaModel(sourceText: "Tram", translatedText: "트램 (전차)"),
        RealmVocaModel(sourceText: "Segway", translatedText: "세그웨이"),
        RealmVocaModel(sourceText: "Pedestrian", translatedText: "보행자"),
        RealmVocaModel(sourceText: "Driver", translatedText: "운전자"),
        RealmVocaModel(sourceText: "Passenger", translatedText: "승객"),
        RealmVocaModel(sourceText: "Pilot", translatedText: "비행사"),
        RealmVocaModel(sourceText: "Captain", translatedText: "선장"),
        RealmVocaModel(sourceText: "Conductor", translatedText: "승객 차장"),
        RealmVocaModel(sourceText: "Cyclist", translatedText: "자전거 타는 사람"),
        RealmVocaModel(sourceText: "Commuter", translatedText: "통근자"),
        RealmVocaModel(sourceText: "Motorist", translatedText: "운전자"),
        RealmVocaModel(sourceText: "Navigator", translatedText: "항해사, 길 안내자"),
        RealmVocaModel(sourceText: "Traffic", translatedText: "교통"),
        RealmVocaModel(sourceText: "Traffic jam", translatedText: "교통 정체"),
        RealmVocaModel(sourceText: "Traffic light", translatedText: "신호등"),
        RealmVocaModel(sourceText: "Road", translatedText: "도로"),
        RealmVocaModel(sourceText: "Street", translatedText: "거리"),
        RealmVocaModel(sourceText: "Highway", translatedText: "고속도로"),
        RealmVocaModel(sourceText: "Lane", translatedText: "차선"),
        RealmVocaModel(sourceText: "Intersection", translatedText: "교차로"),
        RealmVocaModel(sourceText: "Roundabout", translatedText: "로터리, 원형 교차로"),
        RealmVocaModel(sourceText: "Sidewalk/Pavement", translatedText: "보도"),
        RealmVocaModel(sourceText: "Bridge", translatedText: "다리"),
        RealmVocaModel(sourceText: "Tunnel", translatedText: "터널"),
        RealmVocaModel(sourceText: "Railroad", translatedText: "철도"),
        RealmVocaModel(sourceText: "Railway", translatedText: "철도"),
        RealmVocaModel(sourceText: "Platform", translatedText: "플랫폼"),
        RealmVocaModel(sourceText: "Terminal", translatedText: "터미널"),
        RealmVocaModel(sourceText: "Station", translatedText: "역"),
        RealmVocaModel(sourceText: "Stop", translatedText: "정류장"),
        RealmVocaModel(sourceText: "Parking lot", translatedText: "주차장"),
        RealmVocaModel(sourceText: "Garage", translatedText: "차고"),
        RealmVocaModel(sourceText: "Carpool", translatedText: "카풀"),
        RealmVocaModel(sourceText: "Speed limit", translatedText: "속도 제한"),
        RealmVocaModel(sourceText: "Toll", translatedText: "통행료"),
        RealmVocaModel(sourceText: "Ticket", translatedText: "표"),
        RealmVocaModel(sourceText: "Fare", translatedText: "요금"),
        RealmVocaModel(sourceText: "Commute", translatedText: "통근"),
        RealmVocaModel(sourceText: "Public transportation", translatedText: "대중교통"),
        RealmVocaModel(sourceText: "Private transportation", translatedText: "개인 교통수단"),
        RealmVocaModel(sourceText: "Bike lane", translatedText: "자전거 도로"),
        RealmVocaModel(sourceText: "Carpool lane", translatedText: "카풀 전용 차선"),
        RealmVocaModel(sourceText: "Rental car", translatedText: "렌트카"),
        RealmVocaModel(sourceText: "Parking meter", translatedText: "주차 미터기"),
        RealmVocaModel(sourceText: "Valet parking", translatedText: "발렛 주차"),
        RealmVocaModel(sourceText: "Car wash", translatedText: "세차"),
        RealmVocaModel(sourceText: "Traffic sign", translatedText: "도로 표지판"),
        RealmVocaModel(sourceText: "Traffic regulations", translatedText: "교통 규정"),
        RealmVocaModel(sourceText: "License plate", translatedText: "번호판"),
        RealmVocaModel(sourceText: "Public transit", translatedText: "대중 교통"),
        RealmVocaModel(sourceText: "Emissions", translatedText: "배출(가스)"),
        RealmVocaModel(sourceText: "Traffic enforcement", translatedText: "교통 단속"),
        RealmVocaModel(sourceText: "Roadwork", translatedText: "도로 공사"),
        RealmVocaModel(sourceText: "Crosswalk", translatedText: "횡단보도"),
        RealmVocaModel(sourceText: "Bike rack", translatedText: "자전거 보관대"),
        RealmVocaModel(sourceText: "Bicycle lane", translatedText: "자전거 전용 차로"),
        RealmVocaModel(sourceText: "Parking garage", translatedText: "주차 타워"),
        RealmVocaModel(sourceText: "Traffic congestion", translatedText: "교통 체증"),
        RealmVocaModel(sourceText: "Vehicle registration", translatedText: "차량 등록"),
        RealmVocaModel(sourceText: "Carpooling", translatedText: "카풀"),
        RealmVocaModel(sourceText: "Bicycle-sharing", translatedText: "자전거 공유 시스템"),
        RealmVocaModel(sourceText: "Ride-sharing", translatedText: "공유 운송 서비스"),
        RealmVocaModel(sourceText: "Traffic violation", translatedText: "교통 위반"),
        RealmVocaModel(sourceText: "Public transit system", translatedText: "대중교통 시스템"),
        RealmVocaModel(sourceText: "Airport shuttle", translatedText: "공항 셔틀"),
        RealmVocaModel(sourceText: "Pedestrian crossing", translatedText: "보행자 횡단로"),
        RealmVocaModel(sourceText: "Car rental service", translatedText: "렌터카 서비스"),
        RealmVocaModel(sourceText: "Cargo ship", translatedText: "화물선"),
        RealmVocaModel(sourceText: "Electric vehicle", translatedText: "전기 자동차"),
        RealmVocaModel(sourceText: "Hybrid vehicle", translatedText: "하이브리드 자동차"),
        RealmVocaModel(sourceText: "Parking permit", translatedText: "주차 허가증"),
        RealmVocaModel(sourceText: "Traffic control", translatedText: "교통 통제"),
        RealmVocaModel(sourceText: "Commuter rail", translatedText: "통근 전철"),
        RealmVocaModel(sourceText: "Transportation network", translatedText: "교통망"),
        RealmVocaModel(sourceText: "Toll road", translatedText: "유료 도로"),
        RealmVocaModel(sourceText: "Railway station", translatedText: "기차역"),
        RealmVocaModel(sourceText: "Bicycle helmet", translatedText: "자전거 헬멧"),
        RealmVocaModel(sourceText: "High-speed rail", translatedText: "고속 철도"),
        RealmVocaModel(sourceText: "Ride-hailing service", translatedText: "호출형 서비스"),
        RealmVocaModel(sourceText: "Public transit fare", translatedText: "대중교통 요금"),
        RealmVocaModel(sourceText: "Road safety", translatedText: "도로 안전"),
        RealmVocaModel(sourceText: "Transportation infrastructure", translatedText: "교통 인프라")
    ]

}
