//
//  Transportation.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct Transportation {
    let query = "Transportation"
    lazy var transportationVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Vehicle", translatedText: "차량", realmQeury: query),
        RealmVocaModel(sourceText: "Car", translatedText: "자동차", realmQeury: query),
        RealmVocaModel(sourceText: "Truck", translatedText: "트럭", realmQeury: query),
        RealmVocaModel(sourceText: "Bus", translatedText: "버스", realmQeury: query),
        RealmVocaModel(sourceText: "Bicycle", translatedText: "자전거", realmQeury: query),
        RealmVocaModel(sourceText: "Motorcycle", translatedText: "오토바이", realmQeury: query),
        RealmVocaModel(sourceText: "Train", translatedText: "기차", realmQeury: query),
        RealmVocaModel(sourceText: "Subway", translatedText: "지하철", realmQeury: query),
        RealmVocaModel(sourceText: "Boat", translatedText: "보트", realmQeury: query),
        RealmVocaModel(sourceText: "Ship", translatedText: "배", realmQeury: query),
        RealmVocaModel(sourceText: "Aircraft", translatedText: "항공기", realmQeury: query),
        RealmVocaModel(sourceText: "Airplane", translatedText: "비행기", realmQeury: query),
        RealmVocaModel(sourceText: "Helicopter", translatedText: "헬리콥터", realmQeury: query),
        RealmVocaModel(sourceText: "Van", translatedText: "밴", realmQeury: query),
        RealmVocaModel(sourceText: "Scooter", translatedText: "스쿠터", realmQeury: query),
        RealmVocaModel(sourceText: "Taxi", translatedText: "택시", realmQeury: query),
        RealmVocaModel(sourceText: "RV (Recreational Vehicle)",
                       translatedText: "RV(레크리에이션 차량)",
                       realmQeury: query),
        RealmVocaModel(sourceText: "Trailer", translatedText: "트레일러", realmQeury: query),
        RealmVocaModel(sourceText: "Tram", translatedText: "트램 (전차)", realmQeury: query),
        RealmVocaModel(sourceText: "Segway", translatedText: "세그웨이", realmQeury: query),
        RealmVocaModel(sourceText: "Pedestrian", translatedText: "보행자", realmQeury: query),
        RealmVocaModel(sourceText: "Driver", translatedText: "운전자", realmQeury: query),
        RealmVocaModel(sourceText: "Passenger", translatedText: "승객", realmQeury: query),
        RealmVocaModel(sourceText: "Pilot", translatedText: "비행사", realmQeury: query),
        RealmVocaModel(sourceText: "Captain", translatedText: "선장", realmQeury: query),
        RealmVocaModel(sourceText: "Conductor", translatedText: "승객 차장", realmQeury: query),
        RealmVocaModel(sourceText: "Cyclist", translatedText: "자전거 타는 사람", realmQeury: query),
        RealmVocaModel(sourceText: "Commuter", translatedText: "통근자", realmQeury: query),
        RealmVocaModel(sourceText: "Motorist", translatedText: "운전자", realmQeury: query),
        RealmVocaModel(sourceText: "Navigator", translatedText: "항해사, 길 안내자", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic", translatedText: "교통", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic jam", translatedText: "교통 정체", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic light", translatedText: "신호등", realmQeury: query),
        RealmVocaModel(sourceText: "Road", translatedText: "도로", realmQeury: query),
        RealmVocaModel(sourceText: "Street", translatedText: "거리", realmQeury: query),
        RealmVocaModel(sourceText: "Highway", translatedText: "고속도로", realmQeury: query),
        RealmVocaModel(sourceText: "Lane", translatedText: "차선", realmQeury: query),
        RealmVocaModel(sourceText: "Intersection", translatedText: "교차로", realmQeury: query),
        RealmVocaModel(sourceText: "Roundabout", translatedText: "로터리, 원형 교차로", realmQeury: query),
        RealmVocaModel(sourceText: "Sidewalk/Pavement", translatedText: "보도", realmQeury: query),
        RealmVocaModel(sourceText: "Bridge", translatedText: "다리", realmQeury: query),
        RealmVocaModel(sourceText: "Tunnel", translatedText: "터널", realmQeury: query),
        RealmVocaModel(sourceText: "Railroad", translatedText: "철도", realmQeury: query),
        RealmVocaModel(sourceText: "Railway", translatedText: "철도", realmQeury: query),
        RealmVocaModel(sourceText: "Platform", translatedText: "플랫폼", realmQeury: query),
        RealmVocaModel(sourceText: "Terminal", translatedText: "터미널", realmQeury: query),
        RealmVocaModel(sourceText: "Station", translatedText: "역", realmQeury: query),
        RealmVocaModel(sourceText: "Stop", translatedText: "정류장", realmQeury: query),
        RealmVocaModel(sourceText: "Parking lot", translatedText: "주차장", realmQeury: query),
        RealmVocaModel(sourceText: "Garage", translatedText: "차고", realmQeury: query),
        RealmVocaModel(sourceText: "Carpool", translatedText: "카풀", realmQeury: query),
        RealmVocaModel(sourceText: "Speed limit", translatedText: "속도 제한", realmQeury: query),
        RealmVocaModel(sourceText: "Toll", translatedText: "통행료", realmQeury: query),
        RealmVocaModel(sourceText: "Ticket", translatedText: "표", realmQeury: query),
        RealmVocaModel(sourceText: "Fare", translatedText: "요금", realmQeury: query),
        RealmVocaModel(sourceText: "Commute", translatedText: "통근", realmQeury: query),
        RealmVocaModel(sourceText: "Public transportation", translatedText: "대중교통", realmQeury: query),
        RealmVocaModel(sourceText: "Private transportation", translatedText: "개인 교통수단", realmQeury: query),
        RealmVocaModel(sourceText: "Bike lane", translatedText: "자전거 도로", realmQeury: query),
        RealmVocaModel(sourceText: "Carpool lane", translatedText: "카풀 전용 차선", realmQeury: query),
        RealmVocaModel(sourceText: "Rental car", translatedText: "렌트카", realmQeury: query),
        RealmVocaModel(sourceText: "Parking meter", translatedText: "주차 미터기", realmQeury: query),
        RealmVocaModel(sourceText: "Valet parking", translatedText: "발렛 주차", realmQeury: query),
        RealmVocaModel(sourceText: "Car wash", translatedText: "세차", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic sign", translatedText: "도로 표지판", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic regulations", translatedText: "교통 규정", realmQeury: query),
        RealmVocaModel(sourceText: "License plate", translatedText: "번호판", realmQeury: query),
        RealmVocaModel(sourceText: "Public transit", translatedText: "대중 교통", realmQeury: query),
        RealmVocaModel(sourceText: "Emissions", translatedText: "배출(가스)", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic enforcement", translatedText: "교통 단속", realmQeury: query),
        RealmVocaModel(sourceText: "Roadwork", translatedText: "도로 공사", realmQeury: query),
        RealmVocaModel(sourceText: "Crosswalk", translatedText: "횡단보도", realmQeury: query),
        RealmVocaModel(sourceText: "Bike rack", translatedText: "자전거 보관대", realmQeury: query),
        RealmVocaModel(sourceText: "Bicycle lane", translatedText: "자전거 전용 차로", realmQeury: query),
        RealmVocaModel(sourceText: "Parking garage", translatedText: "주차 타워", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic congestion", translatedText: "교통 체증", realmQeury: query),
        RealmVocaModel(sourceText: "Vehicle registration", translatedText: "차량 등록", realmQeury: query),
        RealmVocaModel(sourceText: "Carpooling", translatedText: "카풀", realmQeury: query),
        RealmVocaModel(sourceText: "Bicycle-sharing", translatedText: "자전거 공유 시스템", realmQeury: query),
        RealmVocaModel(sourceText: "Ride-sharing", translatedText: "공유 운송 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic violation", translatedText: "교통 위반", realmQeury: query),
        RealmVocaModel(sourceText: "Public transit system", translatedText: "대중교통 시스템", realmQeury: query),
        RealmVocaModel(sourceText: "Airport shuttle", translatedText: "공항 셔틀", realmQeury: query),
        RealmVocaModel(sourceText: "Pedestrian crossing", translatedText: "보행자 횡단로", realmQeury: query),
        RealmVocaModel(sourceText: "Car rental service", translatedText: "렌터카 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Cargo ship", translatedText: "화물선", realmQeury: query),
        RealmVocaModel(sourceText: "Electric vehicle", translatedText: "전기 자동차", realmQeury: query),
        RealmVocaModel(sourceText: "Hybrid vehicle", translatedText: "하이브리드 자동차", realmQeury: query),
        RealmVocaModel(sourceText: "Parking permit", translatedText: "주차 허가증", realmQeury: query),
        RealmVocaModel(sourceText: "Traffic control", translatedText: "교통 통제", realmQeury: query),
        RealmVocaModel(sourceText: "Commuter rail", translatedText: "통근 전철", realmQeury: query),
        RealmVocaModel(sourceText: "Transportation network", translatedText: "교통망", realmQeury: query),
        RealmVocaModel(sourceText: "Toll road", translatedText: "유료 도로", realmQeury: query),
        RealmVocaModel(sourceText: "Railway station", translatedText: "기차역", realmQeury: query),
        RealmVocaModel(sourceText: "Bicycle helmet", translatedText: "자전거 헬멧", realmQeury: query),
        RealmVocaModel(sourceText: "High-speed rail", translatedText: "고속 철도", realmQeury: query),
        RealmVocaModel(sourceText: "Ride-hailing service", translatedText: "호출형 서비스", realmQeury: query),
        RealmVocaModel(sourceText: "Public transit fare", translatedText: "대중교통 요금", realmQeury: query),
        RealmVocaModel(sourceText: "Road safety", translatedText: "도로 안전", realmQeury: query),
        RealmVocaModel(sourceText: "Transportation infrastructure", translatedText: "교통 인프라", realmQeury: query)
    ]
}
