//
//  TravelActivitiesVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct TravelActivitiesVoca {
    var travelActivitiesVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Travel", translatedText: "여행"),
        RealmVocaModel(sourceText: "Adventure", translatedText: "모험"),
        RealmVocaModel(sourceText: "Explore", translatedText: "탐험하다"),
        RealmVocaModel(sourceText: "Tour", translatedText: "투어"),
        RealmVocaModel(sourceText: "Sightseeing", translatedText: "구경"),
        RealmVocaModel(sourceText: "Hiking", translatedText: "하이킹"),
        RealmVocaModel(sourceText: "Trekking", translatedText: "트레킹"),
        RealmVocaModel(sourceText: "Camping", translatedText: "캠핑"),
        RealmVocaModel(sourceText: "Backpacking", translatedText: "배낭여행"),
        RealmVocaModel(sourceText: "Mountaineering", translatedText: "등산"),
        RealmVocaModel(sourceText: "Cycling", translatedText: "사이클링"),
        RealmVocaModel(sourceText: "Biking", translatedText: "자전거 타기"),
        RealmVocaModel(sourceText: "Road trip", translatedText: "로드 트립"),
        RealmVocaModel(sourceText: "Safari", translatedText: "사파리"),
        RealmVocaModel(sourceText: "Wildlife watching", translatedText: "야생동물 관찰"),
        RealmVocaModel(sourceText: "Snorkeling", translatedText: "스노클링"),
        RealmVocaModel(sourceText: "Scuba diving", translatedText: "스쿠버 다이빙"),
        RealmVocaModel(sourceText: "Surfing", translatedText: "서핑"),
        RealmVocaModel(sourceText: "Beachcombing", translatedText: "해변 산책"),
        RealmVocaModel(sourceText: "Fishing", translatedText: "낚시"),
        RealmVocaModel(sourceText: "Canoeing", translatedText: "카누"),
        RealmVocaModel(sourceText: "Kayaking", translatedText: "카약"),
        RealmVocaModel(sourceText: "Rafting", translatedText: "래프팅"),
        RealmVocaModel(sourceText: "Paragliding", translatedText: "패러글라이딩"),
        RealmVocaModel(sourceText: "Skydiving", translatedText: "스카이다이빙"),
        RealmVocaModel(sourceText: "Bungee jumping", translatedText: "번지 점프"),
        RealmVocaModel(sourceText: "Zip-lining", translatedText: "짚라인"),
        RealmVocaModel(sourceText: "Hot air ballooning", translatedText: "열기구 타기"),
        RealmVocaModel(sourceText: "Horseback riding", translatedText: "승마"),
        RealmVocaModel(sourceText: "Skiing", translatedText: "스키"),
        RealmVocaModel(sourceText: "Snowboarding", translatedText: "스노보드"),
        RealmVocaModel(sourceText: "Ice skating", translatedText: "아이스 스케이팅"),
        RealmVocaModel(sourceText: "Dog sledding", translatedText: "강아지 썰매"),
        RealmVocaModel(sourceText: "Photography", translatedText: "사진촬영"),
        RealmVocaModel(sourceText: "Videography", translatedText: "비디오 촬영"),
        RealmVocaModel(sourceText: "Culture tour", translatedText: "문화 투어"),
        RealmVocaModel(sourceText: "Historical tour", translatedText: "역사 투어"),
        RealmVocaModel(sourceText: "Food tour", translatedText: "음식 투어"),
        RealmVocaModel(sourceText: "Wine tasting tour", translatedText: "와인 시음 투어"),
        RealmVocaModel(sourceText: "Brewery tour", translatedText: "맥주 양조장 투어"),
        RealmVocaModel(sourceText: "Distillery tour", translatedText: "주정공장 투어"),
        RealmVocaModel(sourceText: "Cultural experience", translatedText: "문화 체험"),
        RealmVocaModel(sourceText: "Local cuisine", translatedText: "현지 음식"),
        RealmVocaModel(sourceText: "Festival", translatedText: "축제"),
        RealmVocaModel(sourceText: "Concert", translatedText: "콘서트"),
        RealmVocaModel(sourceText: "Live performance", translatedText: "라이브 공연"),
        RealmVocaModel(sourceText: "Street performance", translatedText: "거리 공연"),
        RealmVocaModel(sourceText: "Museum visit", translatedText: "박물관 방문"),
        RealmVocaModel(sourceText: "Art gallery visit", translatedText: "미술관 방문"),
        RealmVocaModel(sourceText: "Shopping", translatedText: "쇼핑"),
        RealmVocaModel(sourceText: "Souvenir hunting", translatedText: "기념품 구매"),
        RealmVocaModel(sourceText: "Relaxation", translatedText: "휴식"),
        RealmVocaModel(sourceText: "Spa", translatedText: "스파"),
        RealmVocaModel(sourceText: "Massage", translatedText: "마사지"),
        RealmVocaModel(sourceText: "Yoga", translatedText: "요가"),
        RealmVocaModel(sourceText: "Meditation", translatedText: "명상"),
        RealmVocaModel(sourceText: "Cultural immersion", translatedText: "문화 몰입"),
        RealmVocaModel(sourceText: "Learning experience", translatedText: "학습 경험"),
        RealmVocaModel(sourceText: "Volunteering", translatedText: "봉사활동"),
        RealmVocaModel(sourceText: "Homestay", translatedText: "홈스테이"),
        RealmVocaModel(sourceText: "Cooking class", translatedText: "요리 수업"),
        RealmVocaModel(sourceText: "Language class", translatedText: "언어 수업"),
        RealmVocaModel(sourceText: "Local community visit", translatedText: "지역 사회 방문"),
        RealmVocaModel(sourceText: "Adventure sports", translatedText: "모험 스포츠"),
        RealmVocaModel(sourceText: "Extreme sports", translatedText: "익스트림 스포츠"),
        RealmVocaModel(sourceText: "Outdoor activities", translatedText: "야외 활동"),
        RealmVocaModel(sourceText: "Indoor activities", translatedText: "실내 활동"),
        RealmVocaModel(sourceText: "Cultural events", translatedText: "문화 행사"),
        RealmVocaModel(sourceText: "Local guide", translatedText: "현지 가이드"),
        RealmVocaModel(sourceText: "Adventure guide", translatedText: "모험 여행 가이드"),
        RealmVocaModel(sourceText: "Tour leader", translatedText: "투어 리더"),
        RealmVocaModel(sourceText: "Activity planner", translatedText: "활동 기획자"),
        RealmVocaModel(sourceText: "Itinerary", translatedText: "여행 일정"),
        RealmVocaModel(sourceText: "Travel companion", translatedText: "여행 동행자"),
        RealmVocaModel(sourceText: "Local traditions", translatedText: "현지 전통"),
        RealmVocaModel(sourceText: "Customs and rituals", translatedText: "습관과 의식")
    ]

}
