//
//  TravelActivitiesVoca.swift
//  VocaWeaveApp
//
//  Created by 천광조 on 12/20/23.
//

import Foundation

struct TravelActivitiesVoca {
    let query = "TravelActivitiesVoca"
    lazy var travelActivitiesVoca: [RealmVocaModel] = [
        RealmVocaModel(sourceText: "Travel", translatedText: "여행", realmQeury: query),
        RealmVocaModel(sourceText: "Adventure", translatedText: "모험", realmQeury: query),
        RealmVocaModel(sourceText: "Explore", translatedText: "탐험하다", realmQeury: query),
        RealmVocaModel(sourceText: "Tour", translatedText: "투어", realmQeury: query),
        RealmVocaModel(sourceText: "Sightseeing", translatedText: "구경", realmQeury: query),
        RealmVocaModel(sourceText: "Hiking", translatedText: "하이킹", realmQeury: query),
        RealmVocaModel(sourceText: "Trekking", translatedText: "트레킹", realmQeury: query),
        RealmVocaModel(sourceText: "Camping", translatedText: "캠핑", realmQeury: query),
        RealmVocaModel(sourceText: "Backpacking", translatedText: "배낭여행", realmQeury: query),
        RealmVocaModel(sourceText: "Mountaineering", translatedText: "등산", realmQeury: query),
        RealmVocaModel(sourceText: "Cycling", translatedText: "사이클링", realmQeury: query),
        RealmVocaModel(sourceText: "Biking", translatedText: "자전거 타기", realmQeury: query),
        RealmVocaModel(sourceText: "Road trip", translatedText: "로드 트립", realmQeury: query),
        RealmVocaModel(sourceText: "Safari", translatedText: "사파리", realmQeury: query),
        RealmVocaModel(sourceText: "Wildlife watching", translatedText: "야생동물 관찰", realmQeury: query),
        RealmVocaModel(sourceText: "Snorkeling", translatedText: "스노클링", realmQeury: query),
        RealmVocaModel(sourceText: "Scuba diving", translatedText: "스쿠버 다이빙", realmQeury: query),
        RealmVocaModel(sourceText: "Surfing", translatedText: "서핑", realmQeury: query),
        RealmVocaModel(sourceText: "Beachcombing", translatedText: "해변 산책", realmQeury: query),
        RealmVocaModel(sourceText: "Fishing", translatedText: "낚시", realmQeury: query),
        RealmVocaModel(sourceText: "Canoeing", translatedText: "카누", realmQeury: query),
        RealmVocaModel(sourceText: "Kayaking", translatedText: "카약", realmQeury: query),
        RealmVocaModel(sourceText: "Rafting", translatedText: "래프팅", realmQeury: query),
        RealmVocaModel(sourceText: "Paragliding", translatedText: "패러글라이딩", realmQeury: query),
        RealmVocaModel(sourceText: "Skydiving", translatedText: "스카이다이빙", realmQeury: query),
        RealmVocaModel(sourceText: "Bungee jumping", translatedText: "번지 점프", realmQeury: query),
        RealmVocaModel(sourceText: "Zip-lining", translatedText: "짚라인", realmQeury: query),
        RealmVocaModel(sourceText: "Hot air ballooning", translatedText: "열기구 타기", realmQeury: query),
        RealmVocaModel(sourceText: "Horseback riding", translatedText: "승마", realmQeury: query),
        RealmVocaModel(sourceText: "Skiing", translatedText: "스키", realmQeury: query),
        RealmVocaModel(sourceText: "Snowboarding", translatedText: "스노보드", realmQeury: query),
        RealmVocaModel(sourceText: "Ice skating", translatedText: "아이스 스케이팅", realmQeury: query),
        RealmVocaModel(sourceText: "Dog sledding", translatedText: "강아지 썰매", realmQeury: query),
        RealmVocaModel(sourceText: "Photography", translatedText: "사진촬영", realmQeury: query),
        RealmVocaModel(sourceText: "Videography", translatedText: "비디오 촬영", realmQeury: query),
        RealmVocaModel(sourceText: "Culture tour", translatedText: "문화 투어", realmQeury: query),
        RealmVocaModel(sourceText: "Historical tour", translatedText: "역사 투어", realmQeury: query),
        RealmVocaModel(sourceText: "Food tour", translatedText: "음식 투어", realmQeury: query),
        RealmVocaModel(sourceText: "Wine tasting tour", translatedText: "와인 시음 투어", realmQeury: query),
        RealmVocaModel(sourceText: "Brewery tour", translatedText: "맥주 양조장 투어", realmQeury: query),
        RealmVocaModel(sourceText: "Distillery tour", translatedText: "주정공장 투어", realmQeury: query),
        RealmVocaModel(sourceText: "Cultural experience", translatedText: "문화 체험", realmQeury: query),
        RealmVocaModel(sourceText: "Local cuisine", translatedText: "현지 음식", realmQeury: query),
        RealmVocaModel(sourceText: "Festival", translatedText: "축제", realmQeury: query),
        RealmVocaModel(sourceText: "Concert", translatedText: "콘서트", realmQeury: query),
        RealmVocaModel(sourceText: "Live performance", translatedText: "라이브 공연", realmQeury: query),
        RealmVocaModel(sourceText: "Street performance", translatedText: "거리 공연", realmQeury: query),
        RealmVocaModel(sourceText: "Museum visit", translatedText: "박물관 방문", realmQeury: query),
        RealmVocaModel(sourceText: "Art gallery visit", translatedText: "미술관 방문", realmQeury: query),
        RealmVocaModel(sourceText: "Shopping", translatedText: "쇼핑", realmQeury: query),
        RealmVocaModel(sourceText: "Souvenir hunting", translatedText: "기념품 구매", realmQeury: query),
        RealmVocaModel(sourceText: "Relaxation", translatedText: "휴식", realmQeury: query),
        RealmVocaModel(sourceText: "Spa", translatedText: "스파", realmQeury: query),
        RealmVocaModel(sourceText: "Massage", translatedText: "마사지", realmQeury: query),
        RealmVocaModel(sourceText: "Yoga", translatedText: "요가", realmQeury: query),
        RealmVocaModel(sourceText: "Meditation", translatedText: "명상", realmQeury: query),
        RealmVocaModel(sourceText: "Cultural immersion", translatedText: "문화 몰입", realmQeury: query),
        RealmVocaModel(sourceText: "Learning experience", translatedText: "학습 경험", realmQeury: query),
        RealmVocaModel(sourceText: "Volunteering", translatedText: "봉사활동", realmQeury: query),
        RealmVocaModel(sourceText: "Homestay", translatedText: "홈스테이", realmQeury: query),
        RealmVocaModel(sourceText: "Cooking class", translatedText: "요리 수업", realmQeury: query),
        RealmVocaModel(sourceText: "Language class", translatedText: "언어 수업", realmQeury: query),
        RealmVocaModel(sourceText: "Local community visit", translatedText: "지역 사회 방문", realmQeury: query),
        RealmVocaModel(sourceText: "Adventure sports", translatedText: "모험 스포츠", realmQeury: query),
        RealmVocaModel(sourceText: "Extreme sports", translatedText: "익스트림 스포츠", realmQeury: query),
        RealmVocaModel(sourceText: "Outdoor activities", translatedText: "야외 활동", realmQeury: query),
        RealmVocaModel(sourceText: "Indoor activities", translatedText: "실내 활동", realmQeury: query),
        RealmVocaModel(sourceText: "Cultural events", translatedText: "문화 행사", realmQeury: query),
        RealmVocaModel(sourceText: "Local guide", translatedText: "현지 가이드", realmQeury: query),
        RealmVocaModel(sourceText: "Adventure guide", translatedText: "모험 여행 가이드", realmQeury: query),
        RealmVocaModel(sourceText: "Tour leader", translatedText: "투어 리더", realmQeury: query),
        RealmVocaModel(sourceText: "Activity planner", translatedText: "활동 기획자", realmQeury: query),
        RealmVocaModel(sourceText: "Itinerary", translatedText: "여행 일정", realmQeury: query),
        RealmVocaModel(sourceText: "Travel companion", translatedText: "여행 동행자", realmQeury: query),
        RealmVocaModel(sourceText: "Local traditions", translatedText: "현지 전통", realmQeury: query),
        RealmVocaModel(sourceText: "Customs and rituals", translatedText: "습관과 의식", realmQeury: query)
    ]

}
